### ISSUE TITLE
Unable to run the example, Weaviate returns 422 and also unable to run ingest.py class "Paragraph" not found

### ISSUE THREAD

**Issue by vcidst** [hwchase17/chat-langchain#3]
I tried running `python app.py` and asking a question in the GUI,
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

==== date/time: 2023-01-28 15:20:38.954878 ====
inp: What is text summary?
What is text summary?
Traceback (most recent call last):
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 39, in chat
    output = agent({"question": inp, "chat_history": history})
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 146, in __call__
    raise e
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 142, in __call__
    outputs = self._call(inputs)
  File "/Users/ziscore/Work/2023/chat-langchain/chain.py", line 45, in _call
    docs = self.vstore.similarity_search(new_question, k=4)
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/vectorstores/weaviate.py", line 78, in similarity_search
    result = query_obj.with_near_text(content).with_limit(k).do()
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/weaviate/gql/filter.py", line 73, in do
    raise UnexpectedStatusCodeException("Query was not successful", response)
weaviate.exceptions.UnexpectedStatusCodeException: Query was not successful! Unexpected status code: 422, with response body: {'error': [{'message': 'no graphql provider present, this is most likely because no schema is present. Import a schema first!'}]}.
^CKeyboard interruption in main thread... closing server.
^CKeyboard interruption in main thread... closing server.
```

I guess this is because the weaviate URL doesn't have a schema. So I ran,

```
wget -r -A.html https://langchain.readthedocs.io/en/latest/
python3 ingest.py
```

However this returns another error that class "Paragraph" not found. 
```
[...]
Created a chunk of size 1755, which is longer than the specified 1000
Traceback (most recent call last):
  File "ingest.py", line 42, in <module>
    client.schema.delete_class("Paragraph")
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/weaviate/schema/crud_schema.py", line 201, in delete_class
    raise UnexpectedStatusCodeException("Delete class from schema", response)
weaviate.exceptions.UnexpectedStatusCodeException: Delete class from schema! Unexpected status code: 400, with response body: {'error': [{'message': "could not find class 'Paragraph'"}]}.
```

I'm running Python 3.8.13 on MacOS if that makes any difference

**Comment by vcidst** [comment]
I guess that delete Pragraph schema was to delete any existing schema on Weaviate. Since mine was empty, I had to comment it out on the first run
