### ISSUE TITLE
KeyError: 'data` after the first successful answer

### ISSUE THREAD

**Issue by vcidst** [hwchase17/chat-langchain#4]
I'm seeing a constant error for all questions after it answered the first question,

```
==== date/time: 2023-01-28 15:58:56.838016 ====
inp: What are agents?
Traceback (most recent call last):
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 39, in chat
    output = agent({"question": inp, "chat_history": history})
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 146, in __call__
    raise e
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 142, in __call__
    outputs = self._call(inputs)
  File "/Users/ziscore/Work/2023/chat-langchain/chain.py", line 39, in _call
    new_question = self.key_word_extractor.run(
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 175, in run
    return self(kwargs)[self.output_keys[0]]
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 146, in __call__
    raise e
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/base.py", line 142, in __call__
    outputs = self._call(inputs)
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/llm.py", line 87, in _call
    return self.apply([inputs])[0]
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/llm.py", line 78, in apply
    response = self.generate(input_list)
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/chains/llm.py", line 63, in generate
    prompt = self.prompt.format(**selected_inputs)
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/prompts/few_shot.py", line 101, in format
    examples = self._get_examples(**kwargs)
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/prompts/few_shot.py", line 81, in _get_examples
    return self.example_selector.select_examples(kwargs)
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/prompts/example_selector/semantic_similarity.py", line 44, in select_examples
    example_docs = self.vectorstore.similarity_search(query, k=self.k)
  File "/Users/ziscore/Work/2023/chat-langchain/venv/lib/python3.8/site-packages/langchain/vectorstores/weaviate.py", line 80, in similarity_search
    for res in result["data"]["Get"][self._index_name]:
KeyError: 'data'
```

**Comment by TheodorosGalanos** [comment]
Have you found a solution to this? I keep getting the same thing as well.

**Comment by himasha0421** [comment]
Please run `python3 ingest_examples.py` before execute the app.py , otherwise weaviate db hasn't any reference for standalone question generation .
