### ISSUE TITLE
Error: UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' when calling ingest_docs

### ISSUE THREAD

**Issue by Dayton2028** [hwchase17/chat-langchain#42]
Traceback (most recent call last):
  File "/root/work/chat-langchain/ingest.py", line 35, in <module>
    ingest_docs()
  File "/root/work/chat-langchain/ingest.py", line 27, in ingest_docs
    vectorstore = FAISS.from_documents(documents, embeddings)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/base.py", line 116, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/faiss.py", line 344, in from_texts
    embeddings = embedding.embed_documents(texts)
  File "/usr/local/lib/python3.10/dist-packages/langchain/embeddings/openai.py", line 254, in embed_documents
    response = embed_with_retry(
  File "/usr/local/lib/python3.10/dist-packages/langchain/embeddings/openai.py", line 53, in embed_with_retry
    return _completion_with_retry(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/embeddings/openai.py", line 51, in _completion_with_retry
    return embeddings.client.create(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/usr/lib/python3.10/http/client.py", line 1255, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 7: ordinal not in range(256)

I've already tried:
loader = ReadTheDocsLoader("langchain.readthedocs.io/en/latest/")
and 
loader = ReadTheDocsLoader("langchain.readthedocs.io/en/latest/", encoding="utf-8")
And both show above error.

How to solve the problem? Very appreciated

**Comment by findalexli** [comment]
I am having the same issue.

**Comment by Dayton2028** [comment]
Solved. Just delete the quotation marks of openAI api key.

**Comment by lacey1968** [comment]
I spent days trying to fix this. Wish I had seen this post first.
Thank you Dayton2028

**Comment by benfield97** [comment]
could someone expand on the solution here? how can you delete the quotation marks around your api key?

**Comment by jar930** [comment]
Thank you so much you are a lifesaver! I almost had a mental breakdown trying to solve this
