### ISSUE TITLE
 cannot import name 'AsyncCallbackManager' from 'langchain.callbacks.base' (/Users/friahi/Library/Python/3.9/lib/python/site-packages/langchain/callbacks/base.py)

### ISSUE THREAD

**Issue by friahi65** [hwchase17/chat-langchain#69]
the versions in the requirement files were not locked, so the AsyncCallbackManager no longer exists in the langchain/callbacks/base.py.

**Comment by dahaoGPT** [comment]
could u tell me which version I need?

**Comment by friahi65** [comment]
I don't know either, it has to go through langchain and see which version had that AsyncCallbackManager or update the code to the newest version of langchain

**Comment by completelyboofyblitzed** [comment]
'AsyncCallbackManager' can be imported from 'langchain.callbacks.manager' now instead. At least worked for me.

**Comment by caring-SilverNine** [comment]
> 
I'm getting this error, is there any further solution?
"ERROR:root:maximum recursion depth exceeded"

**Comment by SilverNine** [comment]
> 'AsyncCallbackManager' can be imported from 'langchain.callbacks.manager' now instead. At least worked for me.

I'm getting this error, is there any further solution?
ERROR:root:maximum recursion depth exceeded

**Comment by HKAB** [comment]
I managed to run the project (langchain==0.0.154) with the following changes:
- `from langchain.callbacks.manager import AsyncCallbackManager`
- Using shallow copy instead of deep copy (copy.deepcopy ->copy.copy) in [manager.py#L719](https://github.com/hwchase17/langchain/blob/3bd5a99b835fa320d02aa733cb0c0bc4a87724fa/langchain/callbacks/manager.py#L719). It's a problem copying `websocket` in `StreamingLLMCallbackHandler` and `QuestionGenCallbackHandler`. I think there are other ways that doesn't require to change langchain code, just make sure deepcopy work.

**Comment by completelyboofyblitzed** [comment]
@HKAB thank you. Didn't you by chance get the following error `ERROR:root:search() missing 3 required positional arguments: 'k', 'distances', and 'labels'` after switching to `ConversationalRetrievalChain`?

**Comment by dahaoGPT** [comment]
> 

hi , i follow your second step and modify the source code ,but i don't know how to make it work?   i am new to python,thx u.

**Comment by dahaoGPT** [comment]
> I managed to run the project (langchain==0.0.154) with the following changes:
> 
> * `from langchain.callbacks.manager import AsyncCallbackManager`
> * `ERROR:root:maximum recursion depth exceeded`: Using shallow copy instead of deep copy (copy.deepcopy ->copy.copy) in [manager.py#L719](https://github.com/hwchase17/langchain/blob/3bd5a99b835fa320d02aa733cb0c0bc4a87724fa/langchain/callbacks/manager.py#L719). It's a problem copying `websocket` in `StreamingLLMCallbackHandler` and `QuestionGenCallbackHandler`. I think there are other ways that doesn't require to change langchain code, just make sure deepcopy work.
> * Using ConversationalRetrievalChain instead of ChatVectorDBChain [like this pull request](https://github.com/hwchase17/chat-langchain/pull/71)

hi , i follow your second step and modify the source code ,but i don't know how to make it work? i am new to python,thx u.

**Comment by SilverNine** [comment]
> > 'AsyncCallbackManager' can be imported from 'langchain.callbacks.manager' now instead. At least worked for me.
> 
> I'm getting this error, is there any further solution? ERROR:root:maximum recursion depth exceeded

Resolved after updating to langchain==0.0.156.

**Comment by silvacarl2** [comment]
i have the same issue even after updating:

uvicorn main:app --reload --port 9000
INFO:     Will watch for changes in these directories: ['/mnt/d/Dropbox/Developer-Tools/LangChain/chat-langchain']
INFO:     Uvicorn running on http://127.0.0.1:9000 (Press CTRL+C to quit)
INFO:     Started reloader process [1902] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/silvacarl/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/silvacarl/.local/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/silvacarl/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/silvacarl/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/d/Dropbox/Developer-Tools/LangChain/chat-langchain/main.py", line 12, in <module>
    from query_data import get_chain
  File "/mnt/d/Dropbox/Developer-Tools/LangChain/chat-langchain/query_data.py", line 2, in <module>
    from langchain.callbacks.base import AsyncCallbackManager
ImportError: cannot import name 'AsyncCallbackManager' from 'langchain.callbacks.base' (/home/silvacarl/.local/lib/python3.8/site-packages/langchain/callbacks/base.py)

no version of langchain seems to work.

**Comment by xuanlinh91** [comment]
Still have this problem with langchain=0.0.0188

**Comment by r0mdau** [comment]
I opened a PR to solve this issue #91

**Comment by ZhangYi1212** [comment]
langchain==0.0.150 solved the problem
