### ISSUE TITLE
ImportError: cannot import name 'AsyncCallbackManager' from 'langchain.callbacks.base' (/usr/local/lib/python3.9/dist-

### ISSUE THREAD

**Issue by chaser24** [hwchase17/chat-langchain#85]
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/chaseryang/langchain/chat-langchain/main.py", line 12, in <module>
    from query_data import get_chain
  File "/home/chaseryang/langchain/chat-langchain/query_data.py", line 2, in <module>
    from langchain.callbacks.base import AsyncCallbackManager
ImportError: cannot import name 'AsyncCallbackManager' from 'langchain.callbacks.base' (/usr/local/lib/python3.9/dist-packages/langchain/callbacks/base.py)

**Comment by yudexiaozhou** [comment]
use `from langchain.callbacks.manager import AsyncCallbackManager`

**Comment by gabrielspadon** [comment]
@yudexiaozhou Works!

**Comment by doron-kahana** [comment]
Is there an open PR for this issue?

**Comment by r0mdau** [comment]
I opened a PR to solve this issue #91

**Comment by DylanMay** [comment]
> use `from langchain.callbacks.manager import AsyncCallbackManager`

it works
